service: sales-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:*
          Resource: "*"
        - Effect: Allow
          Action:
            - sns:*
          Resource: "*"

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

